apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # Used if Argo CD is running behind reverse proxy under subpath different from /
  # CLI argocd login <IP> --username admin --insecure --grpc-web --grpc-web-root-path "/argocd"
  server.rootpath: "/argocd"
  server.insecure: "true"