variables:
  - name: environment
    value: dev
  - group: azure-dev-data
  - name: azureSubscription
    value: az-dev-spn
  - name: cluster_kubernetes_version
    value: 1.27.3
  - name: private_cluster_enabled
    value: false
  - name: enable_auto_scaling
    value: false
  - name: cluster_sku_tier
    value: "Free"
  - name: load_balancer_sku
    value: "standard"
  - name: public_network_access_enabled
    value: false
  - name: cluster_node_count
    value: 1
  - name: cluster_min_node_count
    value: 1
  - name: cluster_max_node_count
    value: 2
