# azure-pipelines
trigger:
  - none

pool: Default

parameters:
  - name: operation
    type: string
    default: create
    values:
      - create
      - destroy
  - name: access_allowed_source_ips_cidr
    displayName: Comma separated (string) Ips allowed Source to access on server
    type: string
    default: ""
  - name: access_allowed_source_port_range
    displayName: Port range (string) allowed Source to access on server
    type: string
    default: "*"
  - name: access_allowed_destination_ip_cidr
    displayName: Ip Cidr (string) Desitnation range allowed to be access on server
    type: string
    default: "*"
  - name: access_allowed_destination_ports
    displayName: Comma separated (string) Ports allowed Desitnation to access on server
    type: string
    default: '"22","80","443"'

variables:
  - template: ../vars/main-vars.yml
    parameters:
      deploymentName: vm-example

resources:
  repositories:
    - repository: terraform-modules
      type: git
      name: terraform-modules
      ref: main

stages:
  - stage: BuildStage
    jobs:
      - job: BuildJob
        steps:
          - checkout: self
            displayName: Checkout this repo

          - checkout: terraform-modules
            displayName: Checkout terraform-modules

          - task: Bash@3
            name: replace_tokens
            displayName: Replace tokens in main.tf
            inputs:
              targetType: inline
              script: |
                # Common variables
                sed -i 's/__tenantId__/$(tenant_id)/g'                      ${{ variables.tfConfigPath }}
                sed -i 's/__subscriptionId__/$(subscription_id)/g'          ${{ variables.tfConfigPath }}
                sed -i 's/__env__/$(environment)/g'                         ${{ variables.tfConfigPath }}
                sed -i 's/__runtimeGroupName__/$(runtime_group_name)/g'     ${{ variables.tfConfigPath }}
                sed -i 's/__location__/$(resource_location)/g'              ${{ variables.tfConfigPath }}
                sed -i 's/__deploymentPrefix__/$(vm_deployment_prefix)/g'   ${{ variables.tfConfigPath }}

                # Virtual Machine
                sed -i 's/__virtualMachineOSDistribution__/$(vm_os_distro)/g'               ${{ variables.tfConfigPath }}
                sed -i 's/__virtualMachineOSOffer__/$(vm_os_offer)/g'                       ${{ variables.tfConfigPath }}
                sed -i 's/__virtualMachineOSSku__/$(vm_os_sku)/g'                           ${{ variables.tfConfigPath }}
                sed -i 's/__virtualMachineSize__/$(vm_size)/g'                              ${{ variables.tfConfigPath }}
                sed -i 's/__storageAccountType__/$(vm_storage_type)/g'                      ${{ variables.tfConfigPath }}
                sed -i 's/"__PublicIPEnabled__"/$(enable_public_ip)/g'                      ${{ variables.tfConfigPath }}
                sed -i 's|__PublicIpSku__|$(public_ip_sku)|g'                               ${{ variables.tfConfigPath }}
                sed -i 's/__PublicIPAllocationMethod__/$(public_ip_allocation_method)/g'    ${{ variables.tfConfigPath }}
                sed -i 's/__PrivateIPAllocationMethod__/$(private_ip_allocation_method)/g'  ${{ variables.tfConfigPath }}

                sed -i 's/__adminUserName__/$(vm_admin_username)/g'             ${{ variables.tfConfigPath }}
                sed -i 's|__adminSSHKey__|$(admin_ssh_key)|g'                   ${{ variables.tfConfigPath }}

                sed -i 's|__allowSourceAccessPortRange__|${{ parameters.access_allowed_source_port_range }}|g'        ${{ variables.tfConfigPath }}
                sed -i 's|"__allowSourceAccessIpsCidr__"|[${{ parameters.access_allowed_source_ips_cidr }}]|g'        ${{ variables.tfConfigPath }}
                sed -i 's|"__allowDestinationAccessPorts__"|[${{ parameters.access_allowed_destination_ports }}]|g'   ${{ variables.tfConfigPath }}
                sed -i 's|__allowDestinationAccessIpCidr__|${{ parameters.access_allowed_destination_ip_cidr }}|g'    ${{ variables.tfConfigPath }}

                # Terraform state
                sed -i 's/__tfStateResourceGroup__/$(tsStateResourceGroup)/g'   ${{ variables.tfConfigPath }}
                sed -i 's/__tfStateStorageAccName__/$(tsStateStorageAccName)/g' ${{ variables.tfConfigPath }}
                sed -i 's/__tfStateContainer__/$(tsStateContainerName)/g'       ${{ variables.tfConfigPath }}
                sed -i 's/__tfStateKey__/$(tsStateKeyName)/g'                   ${{ variables.tfConfigPath }}

                # Tags
                sed -i 's/__projectCode__/$(tagsProjectCode)/g'    ${{ variables.tfConfigPath }}
                sed -i 's/__invoiceCode__/$(tagsInvoiceCode)/g'    ${{ variables.tfConfigPath }}

          - template: ../templates/pipelines/azure/build-publish-jobs.yml
            parameters:
              azureSubscription: $(azureSubscription)
              repositoryEnvironment: $(environment)
              tfBuildRepoPath: $(tfBuildRepoPath)
              tfConfigRootPath: $(tfConfigRootPath)
              operation: ${{ parameters.operation }}
  - stage: DeployStage
    condition: succeeded()
    jobs:
      - template: ../templates/pipelines/azure/deployment-jobs.yml
        parameters:
          azureSubscription: $(azureSubscription)
          artifactPath: $(artifactUploadPath)
          artifactExtractPath: $(artifactExtractPath)
          deploymentAzDoEnvironment: $(azureDeploymentEnvironment)
          repositoryEnvironment: $(environment)
          operation: ${{ parameters.operation }}
