# azure-pipelines
trigger:
  - none

pool: Default

parameters:
  - name: operation
    type: string
    default: create
    values:
      - create
      - destroy
  - name: access_allowed_source_ips_cidr
    displayName: Comma separated (string) Ips allowed Source to access on server
    type: string
    default: ""

variables:
  - template: ../vars/main-vars.yml
    parameters:
      deploymentName: aks-example

resources:
  repositories:
    - repository: terraform-modules
      type: git
      name: terraform-modules
      ref: main

stages:
  - stage: BuildStage
    jobs:
      - job: BuildJob
        steps:
          - checkout: self
            displayName: Checkout this repo

          - checkout: terraform-modules
            displayName: Checkout terraform-modules

          - task: Bash@3
            name: replace_tokens
            displayName: Replace tokens in main.tf
            inputs:
              targetType: inline
              script: |
                # Common variables
                sed -i 's/__tenantId__/$(tenant_id)/g'                      ${{ variables.tfConfigPath }}
                sed -i 's/__subscriptionId__/$(subscription_id)/g'          ${{ variables.tfConfigPath }}
                sed -i 's/__env__/$(environment)/g'                         ${{ variables.tfConfigPath }}
                sed -i 's/__runtimeGroupName__/$(runtime_group_name)/g'     ${{ variables.tfConfigPath }}
                sed -i 's/__location__/$(resource_location)/g'              ${{ variables.tfConfigPath }}
                sed -i 's/__deploymentPrefix__/$(vm_deployment_prefix)/g'   ${{ variables.tfConfigPath }}

                # Aks
                sed -i 's/__clusterName__/$(cluster_name)/g'                            ${{ variables.tfConfigPath }}
                sed -i 's/__clusterDnsPrefix__/$(cluster_dns_prefix)/g'                 ${{ variables.tfConfigPath }}
                sed -i 's/__clusterAdminGroupAADId__/$(cluster_admin_aad_group_id)/g'   ${{ variables.tfConfigPath }}
                sed -i 's/__clusterLoadBalancerSku___/$(load_balancer_sku)/g'           ${{ variables.tfConfigPath }}
                sed -i 's/__clusterSkuTier___/$(cluster_sku_tier)/g'                    ${{ variables.tfConfigPath }}

                # Aks # Booleans and numbers
                sed -i 's/__clusterKubernetesVersion__/$(cluster_kubernetes_version)/g'         ${{ variables.tfConfigPath }}

                sed -i 's/"__clusterPrivateNetwork__"/$(private_cluster_enabled)/g'                         ${{ variables.tfConfigPath }}
                sed -i 's/"__clusterPubNetAccessEnabled__"/$(public_network_access_enabled)/g'              ${{ variables.tfConfigPath }}
                sed -i 's|"__clusterAuthorizedIps__"|[${{ parameters.access_allowed_source_ips_cidr }}]|g'  ${{ variables.tfConfigPath }}

                sed -i 's/"__clusterAutoScale__"/$(enable_auto_scaling)/g'            ${{ variables.tfConfigPath }}
                sed -i 's/"__clusterNodeCount__"/$(cluster_node_count)/g'             ${{ variables.tfConfigPath }}
                sed -i 's/"__clusterMinNodeCount__"/$(cluster_min_node_count)/g'      ${{ variables.tfConfigPath }}
                sed -i 's/"__clusterMaxModeCount__"/$(cluster_max_node_count)/g'      ${{ variables.tfConfigPath }}

                # Terraform state
                sed -i 's/__tfStateResourceGroup__/$(tsStateResourceGroup)/g'   ${{ variables.tfConfigPath }}
                sed -i 's/__tfStateStorageAccName__/$(tsStateStorageAccName)/g' ${{ variables.tfConfigPath }}
                sed -i 's/__tfStateContainer__/$(tsStateContainerName)/g'       ${{ variables.tfConfigPath }}
                sed -i 's/__tfStateKey__/$(tsStateKeyName)/g'                   ${{ variables.tfConfigPath }}

                # Tags
                sed -i 's/__projectCode__/$(tagsProjectCode)/g'    ${{ variables.tfConfigPath }}
                sed -i 's/__invoiceCode__/$(tagsInvoiceCode)/g'    ${{ variables.tfConfigPath }}

          - template: ../templates/pipelines/azure/build-publish-jobs.yml
            parameters:
              azureSubscription: $(azureSubscription)
              repositoryEnvironment: $(environment)
              tfBuildRepoPath: $(tfBuildRepoPath)
              tfConfigRootPath: $(tfConfigRootPath)
              operation: ${{ parameters.operation }}

  - stage: DeployStage
    condition: succeeded()
    jobs:
      - template: ../templates/pipelines/azure/deployment-jobs.yml
        parameters:
          azureSubscription: $(azureSubscription)
          artifactPath: $(artifactUploadPath)
          artifactExtractPath: $(artifactExtractPath)
          deploymentAzDoEnvironment: $(azureDeploymentEnvironment)
          repositoryEnvironment: $(environment)
          operation: ${{ parameters.operation }}
