kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ops-user-access
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
      - persistenvolumeclaims
      - persistenvolumes
      - pods
      - pods/log
      - services
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - batch/v1
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
      - csidrivers
      - csistoragecapacities
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
      - networkpolicies
    verbs:
      - get
      - watch
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ops-user-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ops-user-access
subjects:
  - kind: Group
    name: __ops_cluster_group_id__
